# Site Settings
lang: en
title: "ekxnumis"
description: "Exploring the world of numismatics"
baseurl: ""
url: "https://ekxnumis.github.io"
logo: "/assets/images/logo.png"

# Author info
author:
  name: "Ekalabya"
  email: "ekxnumis@gmail.com"
  github: "ekxnumis"
  twitter: ""
  linkedin: ""

# Theme settings
theme: bulma-clean-theme


collections:
  docs:
    output: true
  products:
    output: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
social:
  github_username: ekxnumis
  facebook: https://www.facebook.com/
  instagram: https://www.instagram.com/
  threads: https://www.threads.net/
  tiktok: https://www.tiktok.com/
  x: https://www.x.com/
  youtube: https://www.youtube.com/

# Section toggles
show_hero: false
show_callouts: false  


# Content Protection 
enable_content_protection: false

# Sass / SCSS build
sass:
  sass_dir: assets/css
  style: compressed